# SPEC-004: Eye expressions and the shape model

Status: implemented
Verified: 2026-08-26 — all 24 expressions set over serial, drawn, and echoed back
Depends on: 003

## Intent

The eyes carry the owl's whole emotional bandwidth. They are two 160 px round
panels behind small openings in a hand-built head, viewed from a metre or two
away. The design has to survive that.

## Requirements

* **R-004.1** Two colours only: black on white.
* **R-004.2** Every mood from the reference sheet is expressible, plus the states
  the owl needs that the sheet does not cover.
* **R-004.3** Adding or retuning a mood must not mean writing a drawing routine.
* **R-004.4** Expression names, shapes and the enum cannot drift apart silently.
* **R-004.5** Asymmetric shapes must mirror between the eyes, so the pair leans
  toward the beak rather than both leaning the same way.

## Decisions

**Two colours, on purpose.** An earlier version had an iris colour, a specular
highlight and grey eyelids. At this size and distance that detail turned to
mush. `COLOR_BG` / `COLOR_INK` in `include/common.h` are the whole palette.
Do not reintroduce gradients or sparkles — this was a considered removal, not an
omission.

**One parametric renderer, not 21 drawing routines.** `Eyes::drawBlob()` renders
any mood from a row of the `SHAPES[]` table. The base form is a superellipse
(`|x/halfW|^n + |y/halfH|^n = 1`, `n = roundness/10`; 2.0 is a plain ellipse,
~2.6 gives the reference sheet's softly-squared blob) plus four modifiers:

| field | effect | used by |
|---|---|---|
| `topSag` | pushes the top edge down in the middle | annoyed, skeptic, bored, unimpressed |
| `botRise` | pushes the bottom edge up in the middle → crescent | happy, glee, squint, focused |
| `slantIn` | drops the top edge toward the **inner** corner | angry, furious |
| `slantOut` | drops the top edge toward the **outer** corner | worried, sad |
| `yOff` | shifts the shape vertically | blink high / low |
| `asymH` | shortens the right eye only | skeptic (deliberately lopsided) |

Retuning a mood means editing numbers in a table. That is the point.

**Rendering is column-wise.** For each x, the top and bottom edge are computed
independently and the span between them is filled. This is what makes crescents
and dome-down shapes fall out for free; a row-by-row rasteriser could not
express independent edge profiles.

**The slant convention is emotional-standard**: angry lowers the *inner* brow,
worried and sad lower the *outer* one. `drawBlob()` mirrors it via its
`mirrored` argument.

**Names come from one table.** `NAMES[]` backs both `Eyes::nameOf()` (telemetry's
`eye` field) and `Eyes::parseName()` (the `expression` command). `SHAPES[]`,
`NAMES[]` and `EyeExpression` are size-checked against `_COUNT` with
`static_assert`, so a mismatch is a build error rather than a wrong eye.

**Three expressions bypass the table** because they are not eyes: `UPDATE` (a
rotating spinner), `ERROR` (a cross), `SLEEPING` (a single closed bar).
`SEARCHING` and `DETECTING` are aliases of `SUSPICIOUS` and `FOCUSED`.

**Blinks are background-coloured bars** closing in from top and bottom, so a
blink eats into whatever shape is underneath. Auto-blink gap is a random
0.7–2.5 s — deliberately short and irregular, because a regular or sparse blink
reads as a machine idling.

## Verified facts

* All 24 expressions were set over serial, rendered, and echoed back in
  telemetry's `eye` field.
* Design confirmed by the owner against the reference sheet via a preview sheet
  generated by `tools/preview_eyes.py`, which parses `SHAPES[]` out of the C++
  and re-implements the identical maths — so the preview cannot drift from the
  firmware.
* An expression override lasts `EXPRESSION_OVERRIDE_MS` (3 s) before the state
  machine reclaims the eyes. Holding a mood means re-sending faster than that.

## Falsified

* **`fillCircle()` was drawing a quarter of every circle.** It walked one
  Bresenham octant and filled only the columns between `cx±r` and `cx±r/√2`, so
  every circle rendered as two crescents flanking a one-pixel centre line. This
  shipped unnoticed because the eyes had never actually been visible before.
  Replaced with a plain scanline fill — at r ≤ 80 the cost of doing it the
  obvious way is irrelevant.
* **`SLEEPY` was squashed twice**, once by its shape row and again by a
  hard-coded lid override in `currentOpenness()`. The override is gone.
* **`main.cpp` kept a second, hand-maintained name array** (`exprNames[]`)
  indexed by the enum. Every new expression would have shifted it and made
  telemetry report the wrong name. This is why names now come from one table.

## Acceptance

1. `python3 tools/preview_eyes.py && open /tmp/eyes.html` — 24 shapes render and
   match the reference sheet.
2. Send each name from `NAMES[]` as an `expression` command; telemetry's `eye`
   field echoes the same name back.
3. A build with a deliberately mismatched table fails at compile time.

## Open

* Blink smoothness is bounded by frame time (~61 ms per eye). If blinks look
  choppy, the fix is redrawing only the changed band rather than the whole
  160x160 frame, or raising `LCD_SPI_FREQ`.
